# Generated by Django 4.1.1 on 2022-09-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=30, unique=True)),
                ('deleted', models.BooleanField()),
                ('type', models.CharField(choices=[('story', 'Story'), ('job', 'Job'), ('comment', 'Comment')], max_length=10)),
                ('by', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('dead', models.BooleanField()),
                ('kids', models.JSONField()),
                ('descendants', models.IntegerField()),
                ('score', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('parent', models.IntegerField()),
                ('parts', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
