# Generated by Django 4.1.1 on 2022-09-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='dead',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='deleted',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='descendants',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='kids',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='parent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='parts',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
