# Generated by Django 4.1.1 on 2022-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_by_alter_newsitem_dead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
