# Generated by Django 4.1.1 on 2022-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsitem_by_alter_newsitem_dead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
