# Generated by Django 4.1.1 on 2022-09-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='hacker_news_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
